---
title: "MattDataLC"
author: "Tim Szewczyk"
date: "8/29/2017"
output: html_document
---

This file pairs Matt's buckthorn data with the GRANIT landcover classes based on the GPS coordinates he recorded at each subplot. 

```{r setup, include=FALSE}
library(sevcheck); library(tidyverse); theme_set(theme_bw()); library(magrittr)
matt_dir <- "../life_history/Chapter-5-FRAL-Demography/"
matt_gps <- read_csv(paste0(matt_dir, "data/gps/WFF_nhlc.csv")) %>%
  select(X, Y, name, nhlcagg) %>%
  bind_rows(read_csv(paste0(matt_dir, "data/gps/TOFA_nhlc.csv")) %>%
              select(X, Y, name, nhlcagg)) %>%
  mutate(name=stringr::str_to_lower(name))
matt_size <- read_csv(paste0(matt_dir, "outputs/fral.tran.df.csv"))
matt_dens <- read_csv(paste0(matt_dir, "outputs/fral.df.ann.csv"))
```


```{r add_nhlc}
matt_size %<>%
  mutate(name=paste0(site, plot)) %>%
  mutate(nhlc=matt_gps$nhlcagg[match(.$name, matt_gps$name)]) %T>%
  write_csv("data/fral.tran.df.csv")
matt_dens %<>%
  mutate(name=paste0(site, plot)) %>%
  mutate(nhlc=matt_gps$nhlcagg[match(.$name, matt_gps$name)]) %T>%
  write_csv("data/fral.df.ann.csv")
```

